-- Migration number: 0000 	 2023-06-05T02:22:45.795Z
CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEST NOT NULL
);
CREATE TABLE Post (
  id INTEGER NOT NULL PRIMARY KEY,
  authorId INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  published INTEGER NOT NULL,
  createdAt TEXT NOT NULL
  -- FOREIGN KEY (authorId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
